swagger: '2.0'
info:
  title: Messages API
  description: authorisation & Session API
  version: 0.0.1
  license:
    name: I don't know ;))
host: 'delapp:3000'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
x-mojo-around-action": 'Delapp::Controller::Auth::check'
paths:
  /auth/login:
    post:
      tags:
         - Authentification
         - Session
      operationId: loginAuth
      x-mojo-to: "Auth#login"
      description: Login into the system and start session
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: login
          in: formData
          type: string
          description: User's login
        - name: password
          in: formData
          type: string
          format: password
      responses:
        '200':
          $ref: "#/definitions/SuccessLogin"
        '400':
          $ref: "#/definitions/FailedLogin"
  /auth/logout:
    get:
      tags:
         - Session
      operationId: logoutAuth
      x-mojo-to: "Auth#logout"
      description: Finish current session or do nothing if not logged in
      responses:
        '200':
          $ref: "#/definitions/SuccessLogout"
  /auth/logout/{sid}:
    get:
      tags:
         - Session
      operationId: forcelogoutAuth
      x-mojo-to: "Auth#forcelogout"
      description: Finish given session forcefully (should be accesible only by admin)
      parameters:
        - name: sid
          in: path
          type: string
          required: true
      responses:
        '200':
          $ref: "#/definitions/SuccessLogout"
        '404':
          $ref: "#/definitions/FailedLogout"
        '403':
          $ref: "#/definitions/FailedLogout"
           
definitions:
  natural_int:
    type: integer
    format: int64
    minimum: 1
  user_id:
    allOf: 
    - $ref: '#/definitions/natural_int'
    - description : User id in base
  SuccessLogin:
    type: object
    description: "Succesfully logged in answer"
    required:
    - sid
    properties:
      sid:
        type: string
        description: New session's id 
        example: abcdef01234
  SuccessLogout:
    type: object
    description: "Succesfully logged out answer"
    required:
    - sid
    properties:
      sid:
        type: string
        description: Finished session's id 
  FailedLogout:
    type: object
    description: "Log out can't be performed"
    required:
    - sid
    properties:
      sid:
        type: string
        description: Finished session's id 
      error:
        type: string
        description: Error message
  FailedLogin:
    type: object
    description: "Log in failed"
    properties:
      error:
        type: string
        description: Error message
        example: "Login failed"