swagger: '2.0'
info:
  title: Messages API
  description: authorisation & Session API
  version: 0.0.1
  license:
    name: I don't know ;))
host: 'delapp:3000'
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
x-mojo-around-action": 'Delapp::Controller::Auth::check'
paths:
  /user:
    get:
      tags:
         - Session
         - User
      operationId: infoUser
      x-mojo-to: "User#info"
      description: Returns info about currently logged in user
      responses:
        '200':
          $ref: "#/definitions/UserData"
        '404':
          $ref: "#/definitions/NoUser"
    post:
      tags:
         - Session
         - User
      operationId: createUser
      x-mojo-to: "User#create"
      description: Create new temporary user for application
      parameters:
        - name: newuser
          in: body
          schema:
            $ref: '#/definitions/TempUserData'
          required: true 
      responses:
        '201':
          $ref: "#/definitions/UserData"
  /user/registrate:
    put:
      tags:
         - Session
         - User
      operationId: registrateUser
      x-mojo-to: "User#registrate"
      description: Registrate new user (permanent) with email confirmation
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/RegUserData'
          required: true 
      responses:
        '201':
          $ref: "#/definitions/UserData"
        '400':
          $ref: "#/definitions/NoUser"
        '409':
          $ref: "#/definitions/NoUser"
  /user/confirm_registrate/{code}:
    get:
      tags:
         - Session
         - User
      operationId: confirm_registrateUser
      x-mojo-to: "User#confirm_registrate"
      description: Registrate new user (permanent) with email confirmation
      parameters:
        - name: code 
          in: path
          type: string
          required: true 
      responses:
        '200':
          $ref: "#/definitions/Confirm"
        '404':
          $ref: "#/definitions/NoUser"
        '409':
          $ref: "#/definitions/NoUser"
           
definitions:
  natural_int:
    type: integer
    format: int64
    minimum: 1
  user_id:
    allOf: 
    - $ref: '#/definitions/natural_int'
    - description : User id in base
    - readOnly: true
  group_id:
    allOf: 
    - $ref: '#/definitions/natural_int'
    - description : Group id in base
  NoUser:
    type: object
    description: "No active logged in session"
    required:
    - error
    properties:
      error:
        type: string
        description: Error message
  Confirm:
    type: object
    description: "No active logged in session"
    required:
    - code
    properties:
      code:
        type: string
        description: Succesful confirmation code
  UserData:
    type: object
    description: "User data"
    required:
    - login
    properties:
      id:
        $ref: "#/definitions/user_id"
      login:
        type: string
        description: user's login
      active:
        type: boolean
        description: is this user currently active?
      email:
        type: string 
        description: User's email address for communication 
      fullname:
        type: string 
        description: User's full name
      phone:
        type: string 
        description: User's phone number
      groups:
        type: array
        items:
          $ref: "#/definitions/group_id" 
  RegUserData:
    allOf:
      - $ref: '#/definitions/UserData'
      - required:
          - password
          - fullname
          - email
  TempUserData:
    type: object
    description: "Temporary User data on creation"
    required:
    - password
    properties:
      password:
        type: string 
        format: password
        description: User's password (unencrypted)